In [7]:
import numpy as np

# Create a 6x4 matrix with random integer values between 20 and 85
matrix = np.random.randint(low=9, high=16, size=(6,4))

# Print the initial matrix
print(f'Initial Matrix Before Slicing: \n\n {matrix}')

# Add a new row at index 4 that is the sum of rows 0 and 2
matrix[4] = np.sum( matrix[[0,2], :], axis=0)

# Add a new row at index 5 that is the sum of rows 1 and 3
matrix[5] = np.sum( matrix[[1,3], :], axis=0)

# Print the modified matrix
print(f'\n Matrix Result After Slicing: \n\n {matrix}')



Initial Matrix Before Slicing: 

 [[15 11 14 12]
 [ 9  9 14 12]
 [13 13 12 12]
 [12 12 15 11]
 [15 10 14 13]
 [ 9 10  9 15]]

 Matrix Result After Slicing: 

 [[15 11 14 12]
 [ 9  9 14 12]
 [13 13 12 12]
 [12 12 15 11]
 [28 24 26 24]
 [21 21 29 23]]
